# Generated by Django 5.1.4 on 2024-12-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_options_task_priority_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority_order',
            field=models.IntegerField(choices=[(2, 'High'), (1, 'Medium'), (0, 'Low')]),
        ),
    ]
